### ISSUE TITLE
Übersicht verbessern

### ISSUE THREAD

**Issue by B-Schwarz** [HWR-Online-Klausur/web-anwendung#12]
@SuttArt bitte die Beschreibung der Aufgabe hinzufügen 😅

**Comment by SuttArt** [comment]
* Aus `./index.js` alle app.get/post methoden löschen und ein `Router` aus `express` benutzen um besserer Übersicht zu erschaffen. 

* Alle Funktionen mit einen Class umzuwickeln, damit wir später "Benefits" aus OOP nutzen können.

**Comment by SuttArt** [comment]
`Aus ./index.js alle app.get/post methoden löschen und ein Router aus express benutzen um besserer Übersicht zu erschaffen.`  

- [ ] Done

_Offene rhetorische Frage: Müssen wir Classen noch mal verbessern/ändern/noch was? Muss mir anschauen wie OOP in JS funktioniert._

**Was wirklich wichtig ist: Wir brauchen unit tests, module test und e2e tests.**

**Comment by SuttArt** [comment]
`Alle Funktionen mit einen Class umzuwickeln, damit wir später "Benefits" aus OOP nutzen können.`
**DONE**
Frage:
`klausur-parser/parser.js` - müssen wir es auch zu eine Klasse umwandeln? Ich sehe es nicht so. Ich denke, wir können es auch so lassen. 

Ab dem Punkt brauchen wir Tests um alles zu testen!

**Comment by B-Schwarz** [comment]
@SuttArt kannst du noch eine Pull Request erstellen?
